version: '3.4'
services:

  historical_data_feeds:
    network_mode: host
    build: 
      context: ./
      dockerfile: ./historical_data_feeds/Dockerfile
    # command: "python run.py"
    env_file:
      - .env
      - .additional_configs
    environment:
      - NAME=historical_data_feeds

  # live_data_feeds:
  #   network_mode: host
  #   build:
  #     context: ./
  #     dockerfile: ./live_data_feeds/Dockerfile
  #   # command: "python run.py"
  #   env_file:
  #     - .env
  #     - .additional_configs
  #   environment:
  #     - NAME=live_data_feeds

  python_backtester:
    network_mode: host
    build: 
      context: ./
      dockerfile: ./python_backtester/Dockerfile
    # command: "python run.py"
    env_file:
      - .env
      - .additional_configs
    environment:
      - NAME=python_backtester

  python_engine:
    network_mode: host
    build:
      context: ./
      dockerfile: ./python_engine/Dockerfile
    # command: "python run.py"
    env_file:
      - .env
      - .additional_configs
    environment:
      - NAME=python_engine

  python_executor:
    network_mode: host
    build: 
      context: ./
      dockerfile: ./python_executor/Dockerfile
    # command: "python run.py"
    env_file:
      - .env
      - .additional_configs
    environment:
      - NAME=python_executor




# TODO add volume that stores historical data to other strategies on this machne be able to use it.