name: Lint

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Poetry
        uses: snok/install-poetry@v1

      - name: Run linter
        run: |
          poetry install --with dev
          poetry run poe lint

      - name: Check version in pyproject.toml
        run: |
          VERSION=$(grep '^version = ' pyproject.toml | sed 's/version = "\(.*\)"/\1/')
          if [ "$VERSION" != "0.0.0" ]; then
            echo "Version in pyproject.toml is not 0.0.0"
            exit 1
          fi