# Simple workflow for deploying static content to GitHub Pages
name: Deploy static content to Pages

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  # Single deploy job since we're just deploying
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Pages
        uses: actions/configure-pages@v2

      # Setup python
      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9
          
          
      # Install dependencies:
      - name: Install Dependencies
        run: |
          python -m pip install -U sphinx
          python -m pip install sphinx-rtd-theme

      - name: Build docs
        run: |
          cd docs_config
          make html
          cd _build/html
          git init
          touch .nojekyll
          git add -A
          git config --local user.email "actions@github.com"
          git config --local user.name "Github Actions"
          git commit -m 'deploy'

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: './docs_config/_build/html' # The folder the action should deploy.


